# Generated by Django 4.0.1 on 2022-01-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=100)),
                ('rango_edad', models.CharField(choices=[('RU', '18-25'), ('RD', '26-33'), ('RT', '34-40'), ('RC', '40+')], max_length=2)),
                ('sexo', models.CharField(max_length=10)),
                ('red_social_fav', models.CharField(max_length=20)),
                ('prom_FB', models.PositiveIntegerField()),
                ('prom_WA', models.PositiveIntegerField()),
                ('prom_TW', models.PositiveIntegerField()),
                ('prom_IN', models.PositiveIntegerField()),
                ('prom_TK', models.PositiveIntegerField()),
            ],
        ),
    ]
